### ISSUE TITLE
Feature Request - Wine for Linux support, comment out requirement for Admin priviledge

### ISSUE THREAD

**Issue by noabody** [Burnt-o/HaloCheckpointManager#10]
WpfApp3\MainWindow.xaml.cs requires two comments to disable the check.  That part's easy.
``` c++
/*        public static bool IsElevated
        {
            get
            {
                return WindowsIdentity.GetCurrent().Owner
                  .IsWellKnown(WellKnownSidType.BuiltinAdministratorsSid);
            }
        }*/

/*            if (IsElevated == false)
            {
                //popup error message that we need admin privledges, then close the application
                MessageBoxResult messageBoxResult = System.Windows.MessageBox.Show(" HCM needs admin privileges to operate, the application will now close. \n To run as admin, right click the exe and 'Run As Administrator' \n \n If you're (rightfully) cautious of giving software admin privs, \n feel free to inspect/build the source from over at \n github.com/Burnt-o/HaloCheckpointManager ", "Error", System.Windows.MessageBoxButton.OK);
                System.Windows.Application.Current.Shutdown();
            }*/
```
Can't get project to build in vs2022, partly because there are unmet requirements in latest 'HCM.sln':

```
(ConsoleApp1, HCMold) don't exist
(TestingRW and BurntMemory) can be cloned from the repo
(GH_D3D11_Hook, ImGui-DirectX-11-Kiero-Hook) must be hunted down and cloned separately
All need to be at same top level dir as (HaloCheckpointManager)
```

I did finally get to the point where it was starting to build but then fails with CS0117 regarding NTSuspendProcess and NTResumeProcess ('type' does not contain a definition for 'identifier').  I had to retarget SpeedHack for c++ v143.  Debug build fails but Release x64 gets close.

Not enough information to get a good build.  Request make version without Admin checks, which will fail in Wine for Linux, that doesn't support the query method but might still work with this program.  Wine is always Admin.

**Comment by Burnt-o** [comment]
HCM3 no longer requires admin priv. I'll have to setup Wine myself at some point to check if there's any other compatibility issues, or let me know if you find any. Building HCM3 for yourself should also be a lot less of a hassle (er, impossibility) than HCM2 was.
