### ISSUE TITLE
Can't Inject Chekpoints in H2A - Arbiter

### ISSUE THREAD

**Issue by Pedrogas** [Burnt-o/HaloCheckpointManager#11]
When I dump a checkpoint and I wanna use it for later an Error Pops Up, right now is just happening with the level The Arbiter

Extra Info:
 Season 7
 Anti Cheat Off
 Laguage Spanish MX
![hcm error](https://user-images.githubusercontent.com/18622128/235323301-4a8445f0-c91f-4ba0-9e7f-96ee4b2299f2.png)

Also attach checkpoint data
![checkpoint info](https://user-images.githubusercontent.com/18622128/235323373-eab51cca-60d3-4cf3-8a14-07270c452f24.png)

**Comment by manosteele117** [comment]
I have the same issue on the same level. Season 7 as well, anti-cheat off. English language, fwiw. Were you able to learn anything about it?

**Comment by Burnt-o** [comment]
Yeah confirmed there was a lot of people having this issue with HCM2, I couldn't ever quite figure it out though. Issue is fixed in HCM3+ sooo
