### ISSUE TITLE
Spawn point viewer / esp

### ISSUE THREAD

**Issue by terrykeeton97** [Burnt-o/HaloCheckpointManager#13]
Would it be possible to get some sort of ESP so we can see the spawn points and position of entities?

Like when you're in Halo3 foundry and you can set spawn points with the blue markers on the floor, and general boxes to track elites/grunts etc

Thank you

**Comment by Burnt-o** [comment]
I was planning to implement something along these lines in the distance future - a 3d object/entity overlay. Hadn't thought of adding spawn points to that but shouldn't be too hard to add. Anyway that probably won't come for a long while haha
